---

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Join IPA realm
  command: >
    ipa-client-install -p {{ ipa_principal }} -w '{{ ipa_principal_password }}'
    --mkhomedir                  
    --no-ntp
    --domain {{ ipa_domain }}
    --realm {{ ipa_realm }}
    --enable-dns-updates
    --unattended
    --force-join
  register: ipa_client_install
  changed_when: '"client is already configured" not in ipa_client_install.stderr'
  failed_when: false