---

- name: Set timezone to America/Los_Angeles
  timezone:
    name: America/Los_Angeles

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'