---

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=86400

- name: Update all installed packages
  apt: only_upgrade=yes

- name: Install some useful packages
  apt:
    name: '{{ item }}'
    state: present
  with_items:
      - '{{ common_packages }}'
      - '{{ ubuntu_packages }}'

- name: Configure APT automatic updates
  lineinfile:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    line: '{{ item }}'
  with_items:
    - 'APT::Periodic::Download-Upgradeable-Packages "1";'
    - 'APT::Periodic::AutocleanInterval "7";'